#define NOTE_SIXTEENTH 125
#define NOTE_EIGHTH 250
#define NOTE_QUARTER 500
#define NOTE_HALF 1000
#define NOTE_WHOLE 2000

const uint16_t  msc_totalth[] PROGMEM = {
    NOTE_E5, NOTE_EIGHTH,
    NOTE_B5, NOTE_EIGHTH,
    NOTE_CS6, NOTE_EIGHTH,
    NOTE_E6, NOTE_QUARTER,
    NOTE_E6, NOTE_EIGHTH,
    NOTE_B5, NOTE_EIGHTH,
    NOTE_A5, NOTE_EIGHTH,
    NOTE_FS5, NOTE_EIGHTH,
    NOTE_GS5, NOTE_EIGHTH,
    NOTE_FS5, NOTE_EIGHTH,
    NOTE_E5, NOTE_QUARTER,
    NOTE_E5, NOTE_EIGHTH,
    NOTE_DS5, NOTE_EIGHTH,
    NOTE_CS5, NOTE_EIGHTH,
    NOTE_B4, NOTE_EIGHTH,
    NOTE_B5, NOTE_EIGHTH,
    NOTE_GS6, NOTE_EIGHTH,
    NOTE_E6, NOTE_QUARTER,
    NOTE_E6, NOTE_EIGHTH,
    NOTE_B6, NOTE_EIGHTH,
    NOTE_A6, NOTE_EIGHTH,
    NOTE_GS6, NOTE_EIGHTH,
    NOTE_FS6, NOTE_EIGHTH,
    NOTE_E6, NOTE_EIGHTH,
    NOTE_DS6, NOTE_EIGHTH,
    NOTE_CS6, NOTE_EIGHTH,
    NOTE_C6, NOTE_EIGHTH,
    NOTE_B5, NOTE_EIGHTH,
    NOTE_E5, NOTE_SIXTEENTH / 2,
    NOTE_GS5, NOTE_SIXTEENTH / 2,
    NOTE_CS6, NOTE_SIXTEENTH / 2,
    NOTE_E6, NOTE_SIXTEENTH / 2,
    TONES_REPEAT
};

const uint16_t  msc_totalth_low[] PROGMEM = {
    NOTE_E3, NOTE_EIGHTH,
    NOTE_B3, NOTE_EIGHTH,
    NOTE_CS4, NOTE_EIGHTH,
    NOTE_E4, NOTE_QUARTER,
    NOTE_E4, NOTE_EIGHTH,
    NOTE_B3, NOTE_EIGHTH,
    NOTE_A3, NOTE_EIGHTH,
    NOTE_FS3, NOTE_EIGHTH,
    NOTE_GS3, NOTE_EIGHTH,
    NOTE_FS3, NOTE_EIGHTH,
    NOTE_E3, NOTE_QUARTER,
    NOTE_E3, NOTE_EIGHTH,
    NOTE_DS3, NOTE_EIGHTH,
    NOTE_CS3, NOTE_EIGHTH,
    NOTE_B2, NOTE_EIGHTH,
    NOTE_B3, NOTE_EIGHTH,
    NOTE_GS4, NOTE_EIGHTH,
    NOTE_E4, NOTE_QUARTER,
    NOTE_E4, NOTE_EIGHTH,
    NOTE_B4, NOTE_EIGHTH,
    NOTE_A4, NOTE_EIGHTH,
    NOTE_GS4, NOTE_EIGHTH,
    NOTE_FS4, NOTE_EIGHTH,
    NOTE_E4, NOTE_EIGHTH,
    NOTE_DS4, NOTE_EIGHTH,
    NOTE_CS4, NOTE_EIGHTH,
    NOTE_C4, NOTE_EIGHTH,
    NOTE_B3, NOTE_EIGHTH,
    NOTE_E3, NOTE_SIXTEENTH / 2,
    NOTE_GS3, NOTE_SIXTEENTH / 2,
    NOTE_CS4, NOTE_SIXTEENTH / 2,
    NOTE_E4, NOTE_SIXTEENTH / 2,
    TONES_REPEAT
};

const uint16_t snd_collect[] PROGMEM = {
    NOTE_E6, NOTE_SIXTEENTH / 2,
    NOTE_G6, NOTE_SIXTEENTH / 2,
    NOTE_C7, NOTE_SIXTEENTH / 2,
    TONES_END
};

const uint16_t snd_miss[] PROGMEM = {
    NOTE_C7, NOTE_SIXTEENTH / 2,
    NOTE_G6, NOTE_SIXTEENTH / 2,
    NOTE_E6, NOTE_SIXTEENTH / 2,
    TONES_END
};
