#define NOTE_SIXTEENTH 125
#define NOTE_EIGHTH 250
#define NOTE_QUARTER 500
#define NOTE_HALF 1000
#define NOTE_WHOLE 2000

const uint16_t  msc_totalth[] PROGMEM = {
    NOTE_E6, NOTE_EIGHTH,
    NOTE_B6, NOTE_EIGHTH,
    NOTE_CS7, NOTE_EIGHTH,
    NOTE_E7, NOTE_QUARTER,
    NOTE_E7, NOTE_EIGHTH,
    NOTE_B6, NOTE_EIGHTH,
    NOTE_A6, NOTE_EIGHTH,
    NOTE_FS6, NOTE_EIGHTH,
    NOTE_GS6, NOTE_EIGHTH,
    NOTE_FS6, NOTE_EIGHTH,
    NOTE_E6, NOTE_QUARTER,
    NOTE_E6, NOTE_EIGHTH,
    NOTE_DS6, NOTE_EIGHTH,
    NOTE_CS6, NOTE_EIGHTH,
    NOTE_B5, NOTE_EIGHTH,
    NOTE_B6, NOTE_EIGHTH,
    NOTE_GS7, NOTE_EIGHTH,
    NOTE_E7, NOTE_QUARTER,
    NOTE_E7, NOTE_EIGHTH,
    NOTE_B7, NOTE_EIGHTH,
    NOTE_A7, NOTE_EIGHTH,
    NOTE_GS7, NOTE_EIGHTH,
    NOTE_FS7, NOTE_EIGHTH,
    NOTE_E7, NOTE_EIGHTH,
    NOTE_DS7, NOTE_EIGHTH,
    NOTE_CS7, NOTE_EIGHTH,
    NOTE_C7, NOTE_EIGHTH,
    NOTE_B6, NOTE_EIGHTH,
    NOTE_E6, NOTE_SIXTEENTH / 2,
    NOTE_GS6, NOTE_SIXTEENTH / 2,
    NOTE_CS7, NOTE_SIXTEENTH / 2,
    NOTE_E7, NOTE_SIXTEENTH / 2,
    TONES_REPEAT
};
